
import database.DatabaseAppointment;
import deleteChangeFunction.windowCancel;
import deleteChangeFunction.windowChange;
import deleteChangeFunction.windowR;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import doctor.Doctor;

import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JButton;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;


import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suada
 */
public class Startpage extends javax.swing.JFrame {

/*
    private javax.swing.JLayeredPane LogInPane;
    private javax.swing.JLayeredPane MakeAPane;
    private javax.swing.JScrollPane ScrollPane_MakeA_list;
    private javax.swing.JLayeredPane SelectionPane;
    private javax.swing.JButton button_ExportToPdf;
    private javax.swing.JButton button_MakeA_send;
    private javax.swing.JButton button_MakeAppointment;
    private javax.swing.JButton button_ShiftCancelAp;
    private javax.swing.JButton button_test;
    private javax.swing.JComboBox<String> combo_MakeA_healthproblem;
    private javax.swing.JComboBox<String> combobox_MakeA_distance;
    private javax.swing.JComboBox<String> combobox_MakeA_type;
    private javax.swing.JComboBox<String> comboboy_MakeA_time;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel label_LogIn_text2;
    private javax.swing.JLabel label_MakeA_adressinfo;
    private javax.swing.JLabel label_MakeA_bday;
    private javax.swing.JLabel label_MakeA_heading1;
    private javax.swing.JLabel label_MakeA_heading2;
    private javax.swing.JLabel label_MakeA_healthinfo;
    private javax.swing.JLabel label_MakeA_insurancename;
    private javax.swing.JLabel label_MakeA_name;
    private javax.swing.JLabel label_MakeA_reminder;
    private javax.swing.JLabel label_MakeA_type;
    private javax.swing.JLabel label_LogIn_text1;
    private javax.swing.JList<String> list_MakeA_doctorlist;
    private javax.swing.JLabel loginpic;
    private javax.swing.JPasswordField pwfield_LogIn_password;
    private javax.swing.JLayeredPane startseite;
    private javax.swing.JTextField txtfield_LogIn_email;
    private javax.swing.JTextField txtfield_MakeA_adressinfo;
    private javax.swing.JTextField txtfield_MakeA_bday;
    private javax.swing.JTextField txtfield_MakeA_healthinfo;
    private javax.swing.JTextField txtfield_MakeA_insurancename;
    private javax.swing.JTextField txtfield_MakeA_name; */
    

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
        SelectionPane.setVisible(false);
        MakeAPane.setVisible(false);
        //DataSavedIntoDatabase db = new DataSavedIntoDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInPane = new javax.swing.JLayeredPane();
        startseite = new javax.swing.JLayeredPane();
        label_LogIn_text1 = new javax.swing.JLabel();
        button_test = new javax.swing.JButton();
        label_LogIn_text2 = new javax.swing.JLabel();
        label_LogIn_email = new javax.swing.JLabel();
        txtfield_LogIn_email = new javax.swing.JTextField();
        label_LogIn_password = new javax.swing.JLabel();
        pwfield_LogIn_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        SelectionPane = new javax.swing.JLayeredPane();
        button_MakeAppointment = new javax.swing.JButton();
        button_ShiftCancelAp = new javax.swing.JButton();
        button_ExportToPdf = new javax.swing.JButton();
        MakeAPane = new javax.swing.JLayeredPane();
        label_MakeA_name = new javax.swing.JLabel();
        label_MakeA_adressinfo = new javax.swing.JLabel();
        txtfield_MakeA_bday = new javax.swing.JTextField();
        button_MakeA_send = new javax.swing.JButton();
        label_MakeA_bday = new javax.swing.JLabel();
        label_MakeA_healthinfo = new javax.swing.JLabel();
        label_MakeA_type = new javax.swing.JLabel();
        txtfield_MakeA_insurancename = new javax.swing.JTextField();
        label_MakeA_insurancename = new javax.swing.JLabel();
        txtfield_MakeA_name = new javax.swing.JTextField();
        txtfield_MakeA_healthinfo = new javax.swing.JTextField();
        combobox_MakeA_type = new javax.swing.JComboBox<>();
        txtfield_MakeA_adressinfo = new javax.swing.JTextField();
        label_MakeA_heading1 = new javax.swing.JLabel();
        label_MakeA_heading2 = new javax.swing.JLabel();
        combo_MakeA_healthproblem = new javax.swing.JComboBox<>();
        ScrollPane_MakeA_list = new javax.swing.JScrollPane();
        list_MakeA_doctorlist = new javax.swing.JList<>();
        label_MakeA_reminder = new javax.swing.JLabel();
        comboboy_MakeA_time = new javax.swing.JComboBox<>();
        combobox_MakeA_distance = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(700, 1000));
        setLocationByPlatform(true);

        startseite.setBackground(new java.awt.Color(255, 102, 102));
        startseite.setForeground(new java.awt.Color(255, 255, 255));

        label_LogIn_text1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label_LogIn_text1.setText("Welcome to our");

        button_test.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_test.setText("Log in ");
        button_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_testActionPerformed(evt);
            }
        });

        label_LogIn_text2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        label_LogIn_text2.setText("EHS SYSTEM");

        label_LogIn_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_LogIn_email.setText("Email");

        label_LogIn_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_LogIn_password.setText("Password");

        pwfield_LogIn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfield_LogIn_passwordActionPerformed(evt);
            }
        });

        jLabel1.setText("<Bild>");

        startseite.setLayer(label_LogIn_text1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(button_test, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(label_LogIn_text2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(label_LogIn_email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(txtfield_LogIn_email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(label_LogIn_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(pwfield_LogIn_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout startseiteLayout = new javax.swing.GroupLayout(startseite);
        startseite.setLayout(startseiteLayout);
        startseiteLayout.setHorizontalGroup(
            startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startseiteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_LogIn_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_LogIn_text2))
                .addGap(0, 215, Short.MAX_VALUE))
            .addGroup(startseiteLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                        .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfield_LogIn_email, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwfield_LogIn_password, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                        .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_LogIn_password, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_test, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                        .addComponent(label_LogIn_email, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        startseiteLayout.setVerticalGroup(
            startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startseiteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label_LogIn_text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_LogIn_text2)
                .addGap(36, 36, 36)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startseiteLayout.createSequentialGroup()
                        .addComponent(txtfield_LogIn_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_LogIn_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwfield_LogIn_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_LogIn_password))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(button_test, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        button_test.getAccessibleContext().setAccessibleName("");

        LogInPane.setLayer(startseite, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LogInPaneLayout = new javax.swing.GroupLayout(LogInPane);
        LogInPane.setLayout(LogInPaneLayout);
        LogInPaneLayout.setHorizontalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startseite)
        );
        LogInPaneLayout.setVerticalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startseite)
        );

        SelectionPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        button_MakeAppointment.setText("Make an Appointment");
        button_MakeAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_MakeAppointmentMousePressed(evt);
            }
        });

        button_ShiftCancelAp.setText("Shift/Cancel Appointment");
        button_ShiftCancelAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ShiftCancelApActionPerformed(evt);
            }
        });

        button_ExportToPdf.setText("Export to PDF");
        button_ExportToPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExportToPdfActionPerformed(evt);
            }
        });

        SelectionPane.setLayer(button_MakeAppointment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SelectionPane.setLayer(button_ShiftCancelAp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SelectionPane.setLayer(button_ExportToPdf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout SelectionPaneLayout = new javax.swing.GroupLayout(SelectionPane);
        SelectionPane.setLayout(SelectionPaneLayout);
        SelectionPaneLayout.setHorizontalGroup(
            SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionPaneLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_MakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ExportToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ShiftCancelAp, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        SelectionPaneLayout.setVerticalGroup(
            SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionPaneLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(button_MakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(button_ShiftCancelAp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button_ExportToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        button_MakeAppointment.getAccessibleContext().setAccessibleDescription("");

        label_MakeA_name.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_name.setText("Full name:");

        label_MakeA_adressinfo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_adressinfo.setText("Adress information:");

        button_MakeA_send.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        button_MakeA_send.setText("send");
        button_MakeA_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button_MakeA_sendMouseReleased(evt);
            }
        });
        button_MakeA_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MakeA_sendActionPerformed(evt);
            }
        });

        label_MakeA_bday.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_bday.setText("Date of birth: ");

        label_MakeA_healthinfo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_healthinfo.setText("Health information:");

        label_MakeA_type.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_type.setText("Insurance type: ");

        label_MakeA_insurancename.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_insurancename.setText("Insurance name: ");

        combobox_MakeA_type.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        combobox_MakeA_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "private", "public" }));
        combobox_MakeA_type.setToolTipText("");

        label_MakeA_heading1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_MakeA_heading1.setText("Please fill out everything in order to make an appointment.");

        label_MakeA_heading2.setText("Please select the distance of search and your health problem ");

        combo_MakeA_healthproblem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select please>", "general problems", "heart", "lungs", "stomach" }));
        combo_MakeA_healthproblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_MakeA_healthproblemActionPerformed(evt);
            }
        });

        ScrollPane_MakeA_list.setViewportView(list_MakeA_doctorlist);

        label_MakeA_reminder.setText("Remind me in: ");

        comboboy_MakeA_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 minutes", "1 hour", "3 days", "1 week" }));

        combobox_MakeA_distance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no restriction", "2km", "5km", "10km", "15km" }));
        combobox_MakeA_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_MakeA_distanceActionPerformed(evt);
            }
        });

        MakeAPane.setLayer(label_MakeA_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_adressinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_bday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(button_MakeA_send, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_bday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_healthinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_insurancename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_insurancename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_healthinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combobox_MakeA_type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_adressinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_heading1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_heading2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combo_MakeA_healthproblem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(ScrollPane_MakeA_list, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_reminder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(comboboy_MakeA_time, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combobox_MakeA_distance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MakeAPaneLayout = new javax.swing.GroupLayout(MakeAPane);
        MakeAPane.setLayout(MakeAPaneLayout);
        MakeAPaneLayout.setHorizontalGroup(
            MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeAPaneLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_MakeA_send, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_MakeA_heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MakeAPaneLayout.createSequentialGroup()
                            .addComponent(label_MakeA_reminder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboboy_MakeA_time, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MakeAPaneLayout.createSequentialGroup()
                            .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_MakeA_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_MakeA_healthinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(label_MakeA_bday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(label_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_MakeA_adressinfo))
                            .addGap(95, 95, 95)
                            .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfield_MakeA_adressinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_bday, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_healthinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combobox_MakeA_type, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_MakeA_heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MakeAPaneLayout.createSequentialGroup()
                                .addComponent(combobox_MakeA_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_MakeA_healthproblem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrollPane_MakeA_list, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        MakeAPaneLayout.setVerticalGroup(
            MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeAPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_MakeA_heading1)
                .addGap(31, 31, 31)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_adressinfo)
                    .addComponent(txtfield_MakeA_adressinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_bday)
                    .addComponent(txtfield_MakeA_bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_healthinfo)
                    .addComponent(txtfield_MakeA_healthinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_type)
                    .addComponent(combobox_MakeA_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_insurancename)
                    .addComponent(txtfield_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_MakeA_heading2)
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_MakeA_healthproblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_MakeA_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ScrollPane_MakeA_list, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_reminder)
                    .addComponent(comboboy_MakeA_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(button_MakeA_send)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectionPane))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MakeAPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectionPane))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MakeAPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ExportToPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExportToPdfActionPerformed
        // SARDARS CODE
    }//GEN-LAST:event_button_ExportToPdfActionPerformed

    private void button_MakeAppointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MakeAppointmentMousePressed
       MakeAPane.setVisible(true);
       SelectionPane.setVisible(false);
    }//GEN-LAST:event_button_MakeAppointmentMousePressed

    private void button_MakeA_sendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MakeA_sendMouseReleased
       int i;
       // txtfield_name.getText().isEmpty()
       if( (!txtfield_MakeA_name.getText().isEmpty()) && (!txtfield_MakeA_adressinfo.getText().isEmpty()) && (!txtfield_MakeA_bday.getText().isEmpty()) && (!txtfield_MakeA_healthinfo.getText().isEmpty()) && (!txtfield_MakeA_insurancename.getText().isEmpty()) ) {
        //SUADAS CODE    
        //Datenspeichern in Datenbank  
        
        
        // In Variablen speichern
           String db_fname = txtfield_MakeA_name.getText();
           String db_adress = txtfield_MakeA_adressinfo.getText();
           String db_birthday = txtfield_MakeA_bday.getText();
           String db_healthInfo = txtfield_MakeA_healthinfo.getText();
           String db_insuranceName = txtfield_MakeA_insurancename.getText();
           int db_insurance_type_no = combobox_MakeA_type.getItemCount();
           
           try {
               //Connection Datenbank Datei
               
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/e-health-system-database?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin","root","FB2_infoDB");
               
               //Statement st = conn.createStatement();
               
               String sql_query = "insert into person (fname,adress,birthday,healthInfo,insuranceType,insuranceName) values (?,?,?,?,?,?)";
               PreparedStatement pstmt = conn.prepareStatement(sql_query);
               pstmt.setString(1,db_fname);
               pstmt.setString(2,db_adress);
               pstmt.setString(3,db_birthday);
               pstmt.setString(4,db_healthInfo);
               if(db_insurance_type_no == 0){
                   pstmt.setString(5,"private");
               } else {
                   pstmt.setString(5,"public");
               }
               pstmt.setString(6,db_insuranceName);
            //  pstmt.executeUpdate();
              pstmt.executeUpdate(sql_query);
               //pstmt.executeQuery(sql_query);
               conn.commit();
               DatabaseAppointment newAppointment = new DatabaseAppointment();
               newAppointment.fname = txtfield_MakeA_name.getText();
               newAppointment.adress = txtfield_MakeA_adressinfo.getText();
               newAppointment.birthday = txtfield_MakeA_bday.getText();
               newAppointment.healthInfo = txtfield_MakeA_healthinfo.getText();
               newAppointment.insuranceName = txtfield_MakeA_insurancename.getText();
              // newAppointment.insuranceType = combobox_MakeA_type.getItemCount();
    
               
               
               
               
               
               
               
            
           } catch ( SQLException e) {
              JOptionPane.showMessageDialog(null,e);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Startpage.class.getName()).log(Level.SEVERE, null, ex);
           }
       
           JOptionPane.showMessageDialog(null,"Appointment is send.");
           AppointmentCount.appointmentcnt.setappcnt(); //Count wird plus eins genommen
           
           MakeAPane.setVisible(false);
           SelectionPane.setVisible(true);
       } else {
           JOptionPane.showMessageDialog(null,"You need to fill out everything.");
       }
           
    
        /*JOptionPane.showMessageDialog(null,"Appointment is send.");*/
	
    }//GEN-LAST:event_button_MakeA_sendMouseReleased

    private void button_MakeA_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MakeA_sendActionPerformed
       //Save data to database
       
       // So bekommt man allgemein die eingabe

       //test.setText(txtfield_name.getText());
       
    }//GEN-LAST:event_button_MakeA_sendActionPerformed


    //<editor-fold desc="Mahis Code">
    /**
     *
     * @param evt
     */
    private void pwfield_LogIn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfield_LogIn_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfield_LogIn_passwordActionPerformed

    private void combo_MakeA_healthproblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_MakeA_healthproblemActionPerformed
        
      
    if(combobox_MakeA_distance.getSelectedItem() == "no restriction"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement( Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement( Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement( Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement( Doctor.general2.name);
           dlm1.addElement( Doctor.general3.name);
           dlm1.addElement( Doctor.general4.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "2km"){
        
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "5km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "10km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement(Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement(Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement(Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
           dlm1.addElement(Doctor.general3.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "15km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement(Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement(Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement(Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
           dlm1.addElement(Doctor.general3.name);
           dlm1.addElement(Doctor.general4.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
     
            
    //ende
    }//GEN-LAST:event_combo_MakeA_healthproblemActionPerformed

    private void button_ShiftCancelApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ShiftCancelApActionPerformed
        //Noras CODE
         
        
EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					windowR window = new windowR();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

class windowR {

	JFrame frame;

	/**
	 * Launch the application.
	 */
        
	 void main() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					windowR window = new windowR();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public windowR() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		JButton btnNewButton = new JButton("Cancel");
		btnNewButton.setBounds(73, 174, 85, 21);
		frame.getContentPane().add(btnNewButton);
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				System.out.println("cancel");
				windowCancel cancel = new windowCancel();
				cancel.cancelMain();
				frame.setVisible(false);
			}
			
			
		});
		
		JButton btnNewButton_1 = new JButton("Change");
		btnNewButton_1.setBounds(282, 174, 85, 21);
		frame.getContentPane().add(btnNewButton_1);
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				System.out.println("Change");
				windowChange change = new windowChange();
				change.changeMain();
				frame.setVisible(false);
			}
			
			
		});
		
		
		JLabel lblNewLabel = new JLabel("How can we help you?");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 30));
		lblNewLabel.setBounds(47, 32, 351, 92);
		frame.getContentPane().add(lblNewLabel);
	}
}


        
    }//GEN-LAST:event_button_ShiftCancelApActionPerformed

    private void combobox_MakeA_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_MakeA_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_MakeA_distanceActionPerformed

    private void button_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_testActionPerformed
        
        String email = txtfield_LogIn_email.getText();
        String password = String.valueOf(pwfield_LogIn_password.getPassword());

        if(password.isEmpty() && !email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Type in a Password!", "Attention", JOptionPane.CANCEL_OPTION);
        }
        else if(email.isEmpty() && !password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please type in a Username!", "Attention", JOptionPane.CANCEL_OPTION);
        }
        else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please type in a Username and a Password!", "Attention", JOptionPane.CANCEL_OPTION);
        } else {
            // Überprüfung der eingebenen Daten
            //TODO
            SelectionPane.setVisible(true);
            startseite.setVisible(false);
        }
        
        
    }//GEN-LAST:event_button_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startpage().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LogInPane;
    private javax.swing.JLayeredPane MakeAPane;
    private javax.swing.JScrollPane ScrollPane_MakeA_list;
    private javax.swing.JLayeredPane SelectionPane;
    private javax.swing.JButton button_ExportToPdf;
    private javax.swing.JButton button_MakeA_send;
    private javax.swing.JButton button_MakeAppointment;
    private javax.swing.JButton button_ShiftCancelAp;
    private javax.swing.JButton button_test;
    private javax.swing.JComboBox<String> combo_MakeA_healthproblem;
    private javax.swing.JComboBox<String> combobox_MakeA_distance;
    private javax.swing.JComboBox<String> combobox_MakeA_type;
    private javax.swing.JComboBox<String> comboboy_MakeA_time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_LogIn_email;
    private javax.swing.JLabel label_LogIn_password;
    private javax.swing.JLabel label_LogIn_text1;
    private javax.swing.JLabel label_LogIn_text2;
    private javax.swing.JLabel label_MakeA_adressinfo;
    private javax.swing.JLabel label_MakeA_bday;
    private javax.swing.JLabel label_MakeA_heading1;
    private javax.swing.JLabel label_MakeA_heading2;
    private javax.swing.JLabel label_MakeA_healthinfo;
    private javax.swing.JLabel label_MakeA_insurancename;
    private javax.swing.JLabel label_MakeA_name;
    private javax.swing.JLabel label_MakeA_reminder;
    private javax.swing.JLabel label_MakeA_type;
    private javax.swing.JList<String> list_MakeA_doctorlist;
    private javax.swing.JPasswordField pwfield_LogIn_password;
    private javax.swing.JLayeredPane startseite;
    private javax.swing.JTextField txtfield_LogIn_email;
    private javax.swing.JTextField txtfield_MakeA_adressinfo;
    private javax.swing.JTextField txtfield_MakeA_bday;
    private javax.swing.JTextField txtfield_MakeA_healthinfo;
    private javax.swing.JTextField txtfield_MakeA_insurancename;
    private javax.swing.JTextField txtfield_MakeA_name;
    // End of variables declaration//GEN-END:variables
    int distance;
    int distance1;
    int distance2;
    int distance3;
    int distance4;

}
