
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import otherclasses.Doctor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suada
 */
public class Startpage extends javax.swing.JFrame {

    

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
        SelectionPane.setVisible(false);
        MakeAPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInPane = new javax.swing.JLayeredPane();
        startseite = new javax.swing.JLayeredPane();
        label_test = new javax.swing.JLabel();
        button_test = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfield_LogIn_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pwfield_LogIn_password = new javax.swing.JPasswordField();
        loginpic = new javax.swing.JLabel();
        SelectionPane = new javax.swing.JLayeredPane();
        button_MakeAppointment = new javax.swing.JButton();
        button_ShiftCancelAp = new javax.swing.JButton();
        button_ExportToPdf = new javax.swing.JButton();
        MakeAPane = new javax.swing.JLayeredPane();
        label_MakeA_name = new javax.swing.JLabel();
        label_MakeA_adressinfo = new javax.swing.JLabel();
        txtfield_MakeA_bday = new javax.swing.JTextField();
        button_MakeA_send = new javax.swing.JButton();
        label_MakeA_bday = new javax.swing.JLabel();
        label_MakeA_healthinfo = new javax.swing.JLabel();
        label_MakeA_type = new javax.swing.JLabel();
        txtfield_MakeA_insurancename = new javax.swing.JTextField();
        label_MakeA_insurancename = new javax.swing.JLabel();
        txtfield_MakeA_name = new javax.swing.JTextField();
        txtfield_MakeA_healthinfo = new javax.swing.JTextField();
        combobox_MakeA_type = new javax.swing.JComboBox<>();
        txtfield_MakeA_adressinfo = new javax.swing.JTextField();
        label_MakeA_heading1 = new javax.swing.JLabel();
        label_MakeA_heading2 = new javax.swing.JLabel();
        combo_MakeA_healthproblem = new javax.swing.JComboBox<>();
        ScrollPane_MakeA_list = new javax.swing.JScrollPane();
        list_MakeA_doctorlist = new javax.swing.JList<>();
        label_MakeA_reminder = new javax.swing.JLabel();
        comboboy_MakeA_time = new javax.swing.JComboBox<>();
        combobox_MakeA_distance = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(700, 1000));
        setLocationByPlatform(true);

        startseite.setBackground(new java.awt.Color(255, 102, 102));
        startseite.setForeground(new java.awt.Color(255, 255, 255));

        label_test.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label_test.setText("Welcome to our");

        button_test.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_test.setText("Log in ");
        button_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_testActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel3.setText("EHS SYSTEM");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Password");

        pwfield_LogIn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfield_LogIn_passwordActionPerformed(evt);
            }
        });

        startseite.setLayer(label_test, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(button_test, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(txtfield_LogIn_email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(pwfield_LogIn_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startseite.setLayer(loginpic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout startseiteLayout = new javax.swing.GroupLayout(startseite);
        startseite.setLayout(startseiteLayout);
        startseiteLayout.setHorizontalGroup(
            startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_test, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(startseiteLayout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(loginpic)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startseiteLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfield_LogIn_email, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwfield_LogIn_password, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startseiteLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))))
            .addGroup(startseiteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_test, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        startseiteLayout.setVerticalGroup(
            startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startseiteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label_test)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(startseiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startseiteLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtfield_LogIn_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(pwfield_LogIn_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40))
                    .addGroup(startseiteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginpic, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addComponent(button_test, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        button_test.getAccessibleContext().setAccessibleName("");

        LogInPane.setLayer(startseite, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LogInPaneLayout = new javax.swing.GroupLayout(LogInPane);
        LogInPane.setLayout(LogInPaneLayout);
        LogInPaneLayout.setHorizontalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startseite)
        );
        LogInPaneLayout.setVerticalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startseite)
        );

        SelectionPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        button_MakeAppointment.setText("Make an Appointment");
        button_MakeAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_MakeAppointmentMousePressed(evt);
            }
        });

        button_ShiftCancelAp.setText("Shift/Cancel Appointment");
        button_ShiftCancelAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ShiftCancelApActionPerformed(evt);
            }
        });

        button_ExportToPdf.setText("Export to PDF");
        button_ExportToPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExportToPdfActionPerformed(evt);
            }
        });

        SelectionPane.setLayer(button_MakeAppointment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SelectionPane.setLayer(button_ShiftCancelAp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SelectionPane.setLayer(button_ExportToPdf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout SelectionPaneLayout = new javax.swing.GroupLayout(SelectionPane);
        SelectionPane.setLayout(SelectionPaneLayout);
        SelectionPaneLayout.setHorizontalGroup(
            SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionPaneLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_MakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ExportToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ShiftCancelAp, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        SelectionPaneLayout.setVerticalGroup(
            SelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionPaneLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(button_MakeAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(button_ShiftCancelAp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button_ExportToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        button_MakeAppointment.getAccessibleContext().setAccessibleDescription("");

        label_MakeA_name.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_name.setText("Full name:");

        label_MakeA_adressinfo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_adressinfo.setText("Adress information:");

        button_MakeA_send.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        button_MakeA_send.setText("send");
        button_MakeA_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button_MakeA_sendMouseReleased(evt);
            }
        });
        button_MakeA_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MakeA_sendActionPerformed(evt);
            }
        });

        label_MakeA_bday.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_bday.setText("Date of birth: ");

        label_MakeA_healthinfo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_healthinfo.setText("Health information:");

        label_MakeA_type.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_type.setText("Insurance type: ");

        label_MakeA_insurancename.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        label_MakeA_insurancename.setText("Insurance name: ");

        combobox_MakeA_type.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        combobox_MakeA_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "private", "public" }));
        combobox_MakeA_type.setToolTipText("");

        label_MakeA_heading1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_MakeA_heading1.setText("Please fill out everything in order to make an appointment.");

        label_MakeA_heading2.setText("Please select the distance of search and your health problem ");

        combo_MakeA_healthproblem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select please>", "general problems", "heart", "lungs", "stomach" }));
        combo_MakeA_healthproblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_MakeA_healthproblemActionPerformed(evt);
            }
        });

        ScrollPane_MakeA_list.setViewportView(list_MakeA_doctorlist);

        label_MakeA_reminder.setText("Remind me in: ");

        comboboy_MakeA_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 minutes", "1 hour", "3 days", "1 week" }));

        combobox_MakeA_distance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "no restriction", "2km", "5km", "10km", "15km" }));
        combobox_MakeA_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_MakeA_distanceActionPerformed(evt);
            }
        });

        MakeAPane.setLayer(label_MakeA_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_adressinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_bday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(button_MakeA_send, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_bday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_healthinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_insurancename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_insurancename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_healthinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combobox_MakeA_type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(txtfield_MakeA_adressinfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_heading1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_heading2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combo_MakeA_healthproblem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(ScrollPane_MakeA_list, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(label_MakeA_reminder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(comboboy_MakeA_time, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MakeAPane.setLayer(combobox_MakeA_distance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MakeAPaneLayout = new javax.swing.GroupLayout(MakeAPane);
        MakeAPane.setLayout(MakeAPaneLayout);
        MakeAPaneLayout.setHorizontalGroup(
            MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeAPaneLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_MakeA_send, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_MakeA_heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MakeAPaneLayout.createSequentialGroup()
                            .addComponent(label_MakeA_reminder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboboy_MakeA_time, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MakeAPaneLayout.createSequentialGroup()
                            .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_MakeA_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_MakeA_healthinfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(label_MakeA_bday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(label_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_MakeA_adressinfo))
                            .addGap(95, 95, 95)
                            .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfield_MakeA_adressinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_bday, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_healthinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combobox_MakeA_type, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfield_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_MakeA_heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MakeAPaneLayout.createSequentialGroup()
                                .addComponent(combobox_MakeA_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_MakeA_healthproblem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrollPane_MakeA_list, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        MakeAPaneLayout.setVerticalGroup(
            MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeAPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_MakeA_heading1)
                .addGap(31, 31, 31)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_MakeA_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_adressinfo)
                    .addComponent(txtfield_MakeA_adressinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_bday)
                    .addComponent(txtfield_MakeA_bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_healthinfo)
                    .addComponent(txtfield_MakeA_healthinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_type)
                    .addComponent(combobox_MakeA_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_insurancename)
                    .addComponent(txtfield_MakeA_insurancename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_MakeA_heading2)
                .addGap(18, 18, 18)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_MakeA_healthproblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_MakeA_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ScrollPane_MakeA_list, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(MakeAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MakeA_reminder)
                    .addComponent(comboboy_MakeA_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(button_MakeA_send)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectionPane))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MakeAPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectionPane))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MakeAPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ExportToPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExportToPdfActionPerformed
        // SARDARS CODE
    }//GEN-LAST:event_button_ExportToPdfActionPerformed

    private void button_MakeAppointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MakeAppointmentMousePressed
       MakeAPane.setVisible(true);
       SelectionPane.setVisible(false);
    }//GEN-LAST:event_button_MakeAppointmentMousePressed

    private void button_MakeA_sendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MakeA_sendMouseReleased
       int i;
       // txtfield_name.getText().isEmpty()
       if( (!txtfield_MakeA_name.getText().isEmpty()) && (!txtfield_MakeA_adressinfo.getText().isEmpty()) && (!txtfield_MakeA_bday.getText().isEmpty()) && (!txtfield_MakeA_healthinfo.getText().isEmpty()) && (!txtfield_MakeA_insurancename.getText().isEmpty()) ) {
           //Datenspeichern in Datenbank 
           
           
           //
          /* Doctor.KM2.name*/
          
         
           
           
           JOptionPane.showMessageDialog(null,"Appointment is send.");
           MakeAPane.setVisible(false);
           SelectionPane.setVisible(true);
       } else {
           JOptionPane.showMessageDialog(null,"You need to fill out everything.");
       }
           
    
        /*JOptionPane.showMessageDialog(null,"Appointment is send.");*/
	
    }//GEN-LAST:event_button_MakeA_sendMouseReleased

    private void button_MakeA_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MakeA_sendActionPerformed
       //Save data to database
       
       // So bekommt man allgemein die eingabe

       //test.setText(txtfield_name.getText());
       
    }//GEN-LAST:event_button_MakeA_sendActionPerformed

    private void button_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_testActionPerformed
        //MAHI CODE
        String password = String.valueOf(pwfield_LogIn_password.getPassword()); // Casting von char[] zu String
        //statt "suada" und "abc" variablen zur Datenbank hinzufügen
        if( !"suada".equals(txtfield_LogIn_email.getText()) || !"abc".equals(password)){
            JOptionPane.showMessageDialog(null,"Email or password is false");
        } else {
            
            
            //Das alles soll passieren, wenn man erfolgreich eingelogt ist
            button_test.setVisible(false);
            label_test.setVisible(false);
            SelectionPane.setVisible(true);
            startseite.setVisible(false);
            LogInPane.setVisible(false);
        }
    }//GEN-LAST:event_button_testActionPerformed

    private void pwfield_LogIn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfield_LogIn_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfield_LogIn_passwordActionPerformed

    private void combo_MakeA_healthproblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_MakeA_healthproblemActionPerformed
        
      
    if(combobox_MakeA_distance.getSelectedItem() == "no restriction"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement( Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement( Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement( Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement( Doctor.general2.name);
           dlm1.addElement( Doctor.general3.name);
           dlm1.addElement( Doctor.general4.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "2km"){
        
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "5km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "10km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement(Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement(Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement(Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
           dlm1.addElement(Doctor.general3.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
    
    if(combobox_MakeA_distance.getSelectedItem() == "15km"){
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "heart" ){
            
           DefaultListModel<String> dlm1 = new DefaultListModel<>();
            dlm1.addElement(Doctor.heart1.name);
            dlm1.addElement(Doctor.heart2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "lungs" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.lungs1.name);
           dlm1.addElement(Doctor.lungs2.name);
            list_MakeA_doctorlist.setModel(dlm1);      
        }
        if(combo_MakeA_healthproblem.getSelectedItem() == "stomach" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.stomach1.name);
           dlm1.addElement(Doctor.stomach2.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        if(combo_MakeA_healthproblem.getSelectedItem() == "general problems" ){
            DefaultListModel<String> dlm1 = new DefaultListModel<>();
           dlm1.addElement(Doctor.general1.name);
           dlm1.addElement(Doctor.general2.name);
           dlm1.addElement(Doctor.general3.name);
           dlm1.addElement(Doctor.general4.name);
            list_MakeA_doctorlist.setModel(dlm1);
            
        }
        
        
        
    }
     
            
    //ende
    }//GEN-LAST:event_combo_MakeA_healthproblemActionPerformed

    private void button_ShiftCancelApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ShiftCancelApActionPerformed
        //Noras CODE
    }//GEN-LAST:event_button_ShiftCancelApActionPerformed

    private void combobox_MakeA_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_MakeA_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_MakeA_distanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LogInPane;
    private javax.swing.JLayeredPane MakeAPane;
    private javax.swing.JScrollPane ScrollPane_MakeA_list;
    private javax.swing.JLayeredPane SelectionPane;
    private javax.swing.JButton button_ExportToPdf;
    private javax.swing.JButton button_MakeA_send;
    private javax.swing.JButton button_MakeAppointment;
    private javax.swing.JButton button_ShiftCancelAp;
    private javax.swing.JButton button_test;
    private javax.swing.JComboBox<String> combo_MakeA_healthproblem;
    private javax.swing.JComboBox<String> combobox_MakeA_distance;
    private javax.swing.JComboBox<String> combobox_MakeA_type;
    private javax.swing.JComboBox<String> comboboy_MakeA_time;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_MakeA_adressinfo;
    private javax.swing.JLabel label_MakeA_bday;
    private javax.swing.JLabel label_MakeA_heading1;
    private javax.swing.JLabel label_MakeA_heading2;
    private javax.swing.JLabel label_MakeA_healthinfo;
    private javax.swing.JLabel label_MakeA_insurancename;
    private javax.swing.JLabel label_MakeA_name;
    private javax.swing.JLabel label_MakeA_reminder;
    private javax.swing.JLabel label_MakeA_type;
    private javax.swing.JLabel label_test;
    private javax.swing.JList<String> list_MakeA_doctorlist;
    private javax.swing.JLabel loginpic;
    private javax.swing.JPasswordField pwfield_LogIn_password;
    private javax.swing.JLayeredPane startseite;
    private javax.swing.JTextField txtfield_LogIn_email;
    private javax.swing.JTextField txtfield_MakeA_adressinfo;
    private javax.swing.JTextField txtfield_MakeA_bday;
    private javax.swing.JTextField txtfield_MakeA_healthinfo;
    private javax.swing.JTextField txtfield_MakeA_insurancename;
    private javax.swing.JTextField txtfield_MakeA_name;
    // End of variables declaration//GEN-END:variables
    int distance;
    int distance1;
    int distance2;
    int distance3;
    int distance4;
}
